# Configuration for welcome - https://probot.github.io/apps/welcome/

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  :tada: Thanks for opening your first issue here! :tada: Please be sure to follow the issue template.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  :tada: Thanks for opening this pull request! :tada: Please make sure that you have read the contribution guidelines and that you have signed the CLA.
