language: java
jdk: openjdk7
notifications:
  email: false
  slack:
    secure: GrrdAizKa/qMab+Rzb6Zv7sGaXBcEbJjY258wUDheku3DC/TEHler1lgoVrnXxx5PFDXy0ztXnMSJ7Epg8k7+Itf1uxlJUmzm2XIHoJ9LvbmEZvE+lz7v7w4VyVG45m672fWo2FrPQj2FopFcRW8hQiNAY3DcRghFP9JztOlnow=
env:
  global:
    - TERM=dumb
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
after_success: ./gradlew curse -S
